use build_query

DROP TABLE IF EXISTS CLIENT;
    CREATE TABLE CLIENT(
    CLIENTID INT NOT NULL,
    SURNAME NVARCHAR (100) NOT NULL,
    GIVENNAME NVARCHAR (100),
    PRIMARY KEY (CLIENTID),
    GENDER VARCHAR (10) CHECK (GENDER in ('FEMALE','MALE'))

    );

DROP TABLE IF EXISTS TOUR;
    CREATE TABLE TOUR(
    TOURNAME NVARCHAR (100),
    DESCRIPTION NVARCHAR (100)

    );

DROP TABLE IF EXISTS EVENT;
    CREATE TABLE EVENT(
    EVENTYEAR INT,
    EVENTMONTH INT,
    EVENTDAY INT,
    FEE INT

    );

DROP TABLE IF EXISTS BOOKING;
    CREATE TABLE BOOKING(
    DATEBOOKED INT,
    PAYMENT MONEY

    );

    SELECT * FROM CLIENT
    SELECT * FROM TOUR
    SELECT * FROM EVENT
    SELECT * FROM BOOKING